### ISSUE TITLE
Fleshy blows up on current JSONEditor.

### ISSUE THREAD

**Issue by robbrit** [trystan2k/fleshy-jsoneditor#14]
When I use Fleshy, it just blows up on start:
```
jsoneditor.min.js:formatted:367 Uncaught (in promise) TypeError: Cannot read property '$ref' of undefined
    at h._getExternalRefs (jsoneditor.min.js:formatted:367)
    at h._loadExternalRefs (jsoneditor.min.js:formatted:397)
    at h.init (jsoneditor.min.js:formatted:161)
    at new h (jsoneditor.min.js:formatted:134)
    at HTMLElement._initializeEditor (FleshyJsoneditor.js:245)
    at HTMLElement.firstUpdated (FleshyJsoneditor.js:152)
    at HTMLElement.performUpdate (updating-element.ts:772)
    at HTMLElement._callee$ (updating-element.ts:713)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:274)
```

I did fiddle around and there is an `options.schema` value that is used by `JSONEditor`. Adding that in to the default options, it's a new error:

```
FleshyJsoneditor.js:247 Uncaught (in promise) TypeError: this.editor.set is not a function
    at HTMLElement._initializeEditor (FleshyJsoneditor.js:247)
    at HTMLElement.firstUpdated (FleshyJsoneditor.js:152)
    at HTMLElement.performUpdate (updating-element.ts:772)
    at HTMLElement._callee$ (updating-element.ts:713)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:274)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at asyncGeneratorStep (decorators.ts:421)
    at _next (decorators.ts:421)
```

Seems like the `JSONEditor` class is not the same one as expected.

**Comment by trystan2k** [comment]
Hi @robbrit ,

Can you give me more details on how did you used it? Did you executed the demo view (npm run start) or any other? Did you execute the build process?

**Comment by robbrit** [comment]
I just followed the README:
```
npm i @trystan2k/fleshy-jsoneditor@latest
```

Then in my TS file:
```typescript
import '@trystan2k/fleshy-jsoneditor/fleshy-jsoneditor.js';

// ...

render() {
    return html`
        <fleshy-jsoneditor></fleshy-jsoneditor>
    `
}
```

**Comment by trystan2k** [comment]
> I just followed the README:
> 
> ```
> npm i @trystan2k/fleshy-jsoneditor@latest
> ```
> 
> Then in my TS file:
> 
> ```ts
> import '@trystan2k/fleshy-jsoneditor/fleshy-jsoneditor.js';
> 
> // ...
> 
> render() {
>     return html`
>         <fleshy-jsoneditor></fleshy-jsoneditor>
>     `
> }
> ```

Hi @robbrit,

Thanks for your reply.

Are you using any tool to build your component like Rollup, Webpack or other ? I ask because I just did a small test following the same steps you did (using the [@open-wc](https://open-wc.org/) scaffolding) and it worked without problem. If you are using any tool, maybe you need to exclude any transformation on the `jsoneditor.min.js` file (as it is already minified).

I also have created a component in webcomponent.dev [fleshy-ts-example](https://webcomponents.dev/edit/fZOOzEBDcgoYGVWv19WG) and also I don't see any problem.

Do you mind sharing all steps are you using when you serve your component ? Would you be so kind to try the webcomponent.dev entry I created and see if you can reproduce your issue there ?

Thank you !

**Comment by robbrit** [comment]
We are using webpack, but it looks like there was an old version of JSONEditor being included by some old code. I'll close this ticket.

**Comment by trystan2k** [comment]
> We are using webpack, but it looks like there was an old version of JSONEditor being included by some old code. I'll close this ticket.

Yeah, that could be an issue since JSONEditor is not provided as an ESM module but it is registered as a global object in window. If there is any other component/class/module that is also importing JSONEditor with an old version, after Fleshy import, it will cause problem. 

I was looking in an alternative to JSONEditor (maybe CodeMirror) to have it more 'ESM' compatible but didn't get time lately (and for the quick view seems that CodeMirror lack some functionality that JSONEditor has).

Anyway, let me know if you find any other issue if you intend to use Fleshy and solve the issue with the old version of JSONEditor.

Regards!
